### ISSUE TITLE
Stepper housing - Openings in the walls.

### ISSUE THREAD

**Issue by diogorsergio** [Plotyx/plotyx#2]
**Notes:**
May consider opening some of the walls in to allow air to circulated to the stepper motors in case they run warm inside of the fully enclosed housing. Hopefully this doesn't compromise rigidity of the assembly.

**Comment by diogorsergio** [comment]
Added some vents to the side walls, this should help. I think the rigidity of the part is not affected much, the wall is quite thick with 7mm. What do you think @morozgrafix ?

![image](https://user-images.githubusercontent.com/52427475/79334575-72c9ec80-7f18-11ea-87bf-bfc6e7421605.png)

**Comment by morozgrafix** [comment]
Nice. It matches the theme. Are they on the both sides?

In fact it may make it more rigid, depending on the infill settings of the printed part.

**Comment by diogorsergio** [comment]
Yeah, both side walls on both feet. There was clash with the feet that is coupled with the electronics box, but I opened vents in it too. Now it might be better because of the fan airflow, or worse if the fan blows hot air from the electronics into the motor housing. I think it should be fine.

![image](https://user-images.githubusercontent.com/52427475/79336035-ecfb7080-7f1a-11ea-9f1f-84de88971560.png)

**Comment by morozgrafix** [comment]
This is fantastic. I think it's both functional and has pleasing aesthetics. If fan is pulling air out of the box then I would think it will pull air from the motor as well. I'll inspect cross section of the model to get some more details on the vents.
